# Generated by Django 2.1.5 on 2019-01-20 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('uf', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cidades',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='estados',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.Pais'),
        ),
        migrations.AddField(
            model_name='cidades',
            name='estado',
            field=models.ForeignKey(default=None, max_length=5, on_delete=django.db.models.deletion.CASCADE, to='hiring.Estados'),
            preserve_default=False,
        ),
    ]
